Test of Eric Schulte's patch to allow specifying the python interpreter via the =:python= header command. 

* New version of =org-babel-execute:python=
+ This supposedly is in the trunk of org-mode, but my version does not have it
+ If things don't work, try executing the following first:
#+BEGIN_SRC emacs-lisp
  (defun org-babel-execute:python (body params)
    "Execute a block of Python code with Babel.
  This function is called by `org-babel-execute-src-block'."
    (let* ((session (org-babel-python-initiate-session
                     (cdr (assoc :session params))))
           (result-params (cdr (assoc :result-params params)))
           (result-type (cdr (assoc :result-type params)))
           (return-val (when (and (eq result-type 'value) (not session))
                         (cdr (assoc :return params))))
           (preamble (cdr (assoc :preamble params)))
           (org-babel-python-command
            (or (cdr (assoc :python params)) org-babel-python-command))
           (full-body
            (org-babel-expand-body:generic
             (concat body (if return-val (format "\nreturn %s" return-val) ""))
             params (org-babel-variable-assignments:python params)))
           (result (org-babel-python-evaluate
                    session full-body result-type result-params preamble)))
      (org-babel-reassemble-table
       result
       (org-babel-pick-name (cdr (assoc :colname-names params))
                            (cdr (assoc :colnames params)))
       (org-babel-pick-name (cdr (assoc :rowname-names params))
                            (cdr (assoc :rownames params))))))
#+END_SRC

#+RESULTS:
: org-babel-execute:python

* Default python version
#+name: check-python-version
#+BEGIN_SRC python
import sys
return sys.version
#+END_SRC

#+RESULTS: check-python-version
: 3.3.5 |Anaconda 2.1.0 (x86_64)| (default, Sep  2 2014, 13:57:31) 
: [GCC 4.2.1 (Apple Inc. build 5577)]

This is the control experiment. 

* Custom python version
#+BEGIN_SRC python :python /Users/will/anaconda/envs/py27/bin/python
import sys
return sys.version
#+END_SRC

#+RESULTS:
: 2.7.8 |Anaconda 2.1.0 (x86_64)| (default, Aug 21 2014, 15:21:46) 
: [GCC 4.2.1 (Apple Inc. build 5577)]

This works.

* Test using call syntax
It is necessary to put the =:python= command in the /inside header arguments/, which go in square brackets before the function arguments. 

#+call: check-python-version[:python /Users/will/anaconda/envs/py27/bin/python]() 

#+RESULTS:
: 2.7.5 |Anaconda 1.8.0 (x86_64)| (default, Oct 24 2013, 07:02:20) 
: [GCC 4.0.1 (Apple Inc. build 5493)]

So that works fine, but beware that the following does not: 

#+call: check-python-version() :python /Users/will/anaconda/envs/py27/bin/python

#+RESULTS:
: 3.3.5 |Anaconda 1.9.1 (x86_64)| (default, Mar 10 2014, 11:22:25) 
: [GCC 4.0.1 (Apple Inc. build 5493)]


* Sacha Chua's alternative solution using a tag and advice

This lisp code must be evaluated first
#+begin_src emacs-lisp
(defadvice org-babel-execute:python (around will activate)
  (if (member "python2" (org-get-tags-at))
    (let ((org-babel-python-command "/Users/will/anaconda/envs/py27/bin/python"))
      ad-do-it)
    ad-do-it))
#+end_src

#+RESULTS:
: org-babel-execute:python

** Sacha direct test                                                :python2:
This works when the code block is directly evaluated
#+name: second-check-python-version
#+BEGIN_SRC python
import sys
return sys.version
#+END_SRC

#+RESULTS:
: 2.7.5 |Anaconda 1.8.0 (x86_64)| (default, Oct 24 2013, 07:02:20) 
: [GCC 4.0.1 (Apple Inc. build 5493)]

** Sacha call test one                                              :python2:
When calling another code block, what matters is that the tag is on the header where the block is defined, so this does not work
#+call: check-python-version()

#+RESULTS:
: 3.3.5 |Anaconda 1.9.1 (x86_64)| (default, Mar 10 2014, 11:22:25) 
: [GCC 4.0.1 (Apple Inc. build 5493)]


** Sacha call test two
But this does
#+call: second-check-python-version()

#+RESULTS:
: 2.7.5 |Anaconda 1.8.0 (x86_64)| (default, Oct 24 2013, 07:02:20) 
: [GCC 4.0.1 (Apple Inc. build 5493)]


* Ian Barton's alternative proposed solution with shebang
Does not work for direct evaluation with =C-c C-c=
#+begin_src python :shebang #!/Users/will/anaconda/envs/py27/bin/python :tangle py2-test.py :exports none :noweb yes :results output
import sys
print(sys.version)
#+end_src

#+RESULTS:
: 3.3.5 |Anaconda 1.9.1 (x86_64)| (default, Mar 10 2014, 11:22:25) 
: [GCC 4.0.1 (Apple Inc. build 5493)]

But does work with tangling to a file first
#+BEGIN_SRC sh :results verbatim
./py2-test.py
#+END_SRC

#+RESULTS:
: 2.7.5 |Anaconda 1.8.0 (x86_64)| (default, Oct 24 2013, 07:02:20) 
: [GCC 4.0.1 (Apple Inc. build 5493)]

